#pod app:server e outro com rótulo app:cache no mesmo nó
apiVersion: v1
kind: Pod
metadata:
  name: server
labels:
  app: server
  spec:
  affinity:
    podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution: 
    labelSelector:
      - matchExpressions:
      - key: app
        operator: In
        values: ["cache"]
        topologyKey: kubernetes.io/hostname