version: '3'
services:
  mysqlsrv:
    image: mysql:5.7.31
    environment:
      MYSQL_ROOT_PASSWORD: "1921681254"
      MYSQL_DATABASE: "project01"
      TZ: "America/Sao_Paulo"
    ports:
      - "3306:3306"
    volumes:
      - /home/arthur/mysql:/var/lib/mysql

  srvpgsql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1921681254"
      POSTGRES_DB: project01
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    volumes:
      - /home/arthur/postgres:/var/lib/postgresql/data

      