#Exemplo de backup do conteúdo de seus volumes persistentes

apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: aws-default
  namespace: velero
spec:
  provider: aws
  config:
  region: us-east-1