Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "wordpress" do |w|
	w.vm.network "private_network", ip: "192.168.56.4"

   config.vm.synced_folder ".ssh-keys", "/ssh-keys"

   w.vm.provision "shell",
   inline: "cat /ssh-keys/vagrant_key.pub >> .ssh/authorized_keys", run: "always"

  end

  config.vm.define "mysql" do |m|
   m.vm.network "private_network", ip: "192.168.56.5"

   config.vm.synced_folder ".ssh-keys", "/ssh-keys"

   m.vm.provision "shell",
   inline: "cat /ssh-keys/vagrant_key.pub >> .ssh/authorized_keys", run: "always"
   
  end

  config.vm.provider "virtualbox" do |v|
	   v.memory = 1024
  end
end
