version: '1.0'
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mypost
      POSTGRES_PASSWORD: 1921681254
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    postgres-db-data:
        name: postgres-db-data