apiVersion: v1 
kind: Pod
metadata:
  name: pod-volume
  labels:
    name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
     limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts: 
    - mountPath: /mnt 
      name: volume-one

  - name: jenkins-container
    image: jenkins:2.60.3
    resources:
     limits:
        memory: "512Mi"
        cpu: "500m"
    volumeMounts: 
    - mountPath: /mnt 
      name: volume-one

  volumes: 
    - name: volume-one
      hostPath: 
        path: /data/volume-one
        type: DirectoryOrCreate
