#exemplo de um manifesto de ClusterRole que concede acesso de leitura a dados sigilosos em qualquer namespace:

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]