apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
