apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: pod-1
spec:
  containers:
  - name: container-pod-1
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

